version: '3.7'

endpoints:
  result:
    - path: /
      service: result
      port: 4000
  vote:
    - path: /
      service: vote
      port: 8080

networks:
  ns:
    external: false

services:

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - ns

  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - ns

  postgresql:
    image: docker.io/bitnami/postgresql:14
    environment:
      - POSTGRES_PASSWORD=okteto
      - POSTGRES_USER=okteto
      - POSTGRES_DB=votes
    ports:
      - '5432:5432'
    networks:
      - ns

  result: 
    build:
      context: ./result
    environment:
      - PORT=4000  
    ports:
      - "4000:4000"
    depends_on:
      - zookeeper
      - postgresql
    networks:
      - ns

  vote: 
    build:
      context: ./vote
    environment:
      - PORT=8080    
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - postgresql
    networks:
      - ns

  worker: 
    build:
      context: ./worker
    depends_on:
      - zookeeper
      - postgresql
    networks:
      - ns

volumes:
  kafka_data:
    driver: local
  zookeeper_data:
    driver: local

