services:

  result:
    build:
      context: result
    ports:
      - 4000:4000
    command: nodemon server.js
    depends_on:
      - postgresql
    volumes:
      - result:/app

  vote:
    build:
      context: vote
    command: mvn spring-boot:run
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - kafka
      - postgresql
    volumes:
      - vote:/app

  worker:
    build:
      context: worker
    depends_on:
      - postgresql
      - kafka

  postgresql:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=okteto
      - POSTGRES_USER=okteto
      - POSTGRES_DB=votes
    ports:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.8.1
    ports:
      - 9092
      - 9093
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
    volumes:
      - kafka-data:/tmp/kraft-combined-logs

volumes:
  result:
  vote:
  postgres-data:
  kafka-data:
