services:

  result:
    build:
      context: result
    ports:
      - 4000:4000
    command: nodemon server.js
    depends_on:
      - postgresql
      - kafka
    volumes:
      - result:/app

  vote:
    build:
      context: vote
    command: mvn spring-boot:run
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - postgresql
      - kafka
    volumes:
      - vote:/app

  worker:
    build:
      context: worker
    depends_on:
      - postgresql
      - kafka

  postgresql:
    image: docker.io/bitnami/postgresql:14
    environment:
      - POSTGRES_PASSWORD=okteto
      - POSTGRES_USER=okteto
      - POSTGRES_DB=votes
    ports:
      - 5432

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - 2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.1
    ports:
      - 9092
      - 9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
