services:
  result: 
    build:
      context: result
    ports:
      - 4000:4000
    command: nodemon server.js
    depends_on:
      - postgresql
    volumes:
      - result:/app

  vote:
    build:
      context: vote
    command: mvnw spring-boot:run
    ports:
      - 8080:8080
    depends_on:
      - postgresql
    volumes:
      - vote:/app

  worker:
    build:
      context: worker
    depends_on:
      - postgresql
    volumes:
      - worker:/app

  postgresql:
    image: docker.io/bitnami/postgresql:14
    environment:
      - POSTGRES_PASSWORD=okteto
      - POSTGRES_USER=okteto
      - POSTGRES_DB=votes
    ports:
      - 5432
